### PR TITLE
Copying the 'stub.apk' file used by the latest versions of Magisk Alpha.

### PR DESCRIPTION
**Pull request by fvrmatteo**
Related to https://github.com/newbit1/rootAVD/issues/39: adds support to the latest versions of Magisk Alpha that need an additional `stub.apk` file.

### CODE REVIEW

**Comment by newbit1** [comment]
Wait a minute...
You are saying this stub.apk file is important to add?
What is the purpose of this file and what does it do?
And should i have add this the whole time?

**Comment by newbit1** [comment]
Ok great, I couldn't merge it directly because the script has changed due to my last mods.
But your PR is implemented and works very well. It rolls out with the next Push.
It seems this stub.apk is only present in Alpha?!
Thank you for your help, very much appreciated.

**Comment by fvrmatteo** [comment]
Glad it works, I simply added the missing operations that Magisk Alpha is doing when patching the `boot.img`. The `stub.apk` seems to be the [Magisk Stub](https://github.com/topjohnwu/Magisk/tree/master/stub) adapted to contain the Magisk Alpha update URL. The original purpose was better hiding the Magisk application (e.g. the classes have random names, the strings are encrypted and the code is dynamically loaded), but not sure how it evolved with time and how exactly Magisk Alpha is using it.

I would say it's just needed since the release of Magisk Alpha that started adding it during the `boot.img` patching.

**Comment by newbit1** [comment]
ok got it, thanks.
How did you get the older version from Magisk Alpha?
I can't find any history of it.

**Comment by fvrmatteo** [comment]
Here you can find the APK files for each release I mentioned (and older ones): https://t.me/magiskalpha.

There's also a private channel, but the releases you find in the channel I shared are basically the same.

**Comment by newbit1** [comment]
Thanks, but I cant parse this history from telegram in my script. Is there anywhere a github source with this versions?

**Pull request closed without merging**
